name: ecom_app_flutter
description: A new Flutter application.
# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^0.19.2+1
  cupertino_icons: ^1.0.0
  country_code_picker: ^1.7.0
  pin_code_fields: ^6.1.0
  carousel_slider: ^3.0.0
  fluttertoast: ^7.1.8

dev_dependencies:
  flutter_test:
    sdk: flutter


# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/
